version: "3.9"

services:
  db:
    image: mysql:5.7
    container_name: photovault-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: photovault
      MYSQL_USER: pvuser
      MYSQL_PASSWORD: pvpass
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - pvnet
    restart: always

  internal:
    build: ./internal
    container_name: photovault-internal
    networks:
      - pvnet
    restart: always
    # internal service is intentionally *not* exposed to host
    expose:
      - "8080"

  web:
    build: ./web
    container_name: photovault-web
    depends_on:
      - db
      - internal
    environment:
      DATABASE_HOST: db
      DATABASE_USER: pvuser
      DATABASE_PASSWORD: pvpass
      DATABASE_NAME: photovault
    ports:
      - "5000:5000"
    networks:
      - pvnet
    restart: always

volumes:
  db_data:

networks:
  pvnet:
